### ISSUE TITLE
Codebase changes to make before v1.0

### ISSUE THREAD

**Issue by bashbaugh** [Simply-Synonyms/simply-synonyms#1]
There are a few codebase changes that we'll need to make before V1.0:

- ~~As more code is added just using plain content scripts will become unmanageable so we need to integrate Webpack and/or Babel so that we can get ESscript modules, features, minification, etc.~~ :heavy_check_mark: 
- TESTS. We need tests but I'm lazy so we don't have them yet, but we definitely need to add them before we get too many more features.
- Isn't really related to this issue but we should prevent unauthorized API access by requiring at least an anonymous firebase idToken with each request

I've also thought about adding a framework such as React or Svelte to make development easier as elements are added. However, considering that one of the goals of Simply Synonyms is to have as minimalistic a UI as possible, and be as fast as possible, I'm not quite sure yet whether this is necessary.

**Comment by scitronboy** [comment]
I've refactored the extension to use Webpack and Babel. This ensures that we can write code using ES modules and the latest js features and it will automatically compile the background script, content script and popup into single minified CSS and JS bundles.

**Comment by bashbaugh** [comment]
- Added Typescript and Preact for faster, smoother development

**Comment by bashbaugh** [comment]
Closing as this doesn't serve much purpose
